name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: latest

      - name: Run tests
        run: clojure -Atest
      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: target/coverage/index.html

      - name: build
        run: clojure -Auberjar
        
      - uses: actions/upload-artifact@v2
        with:
          name: uberjar
          path: target/backend*.jar
